import * as webpack from "webpack";
import * as merge from "webpack-merge";
import * as HtmlWebpackPlugin from "html-webpack-plugin";
import * as baseConfig from "./base";

module.exports = merge.smart(baseConfig, {
  // Add hot reloading in development
  entry: [
    "eventsource-polyfill", // Necessary for hot reloading with IE
    "webpack-hot-middleware/client",
    "./src/app/app.js", // Start with js/app.js
  ],

  // Don"t use hashes in dev mode for better performance
  output: {
    filename: "[name].js",
    chunkFilename: "[name].chunk.js",
  },

  // Add development plugins
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: "vendor",
      children: true,
      minChunks: 2,
      async: true,
    }),
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new webpack.NoEmitOnErrorsPlugin(),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "src/app/index.html",
    }),
  ],

  devtool: "source-map",

  // TODO - find a better way to set react-hmre
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["react-hmre"],
          },
        },
      },
    ],
  },
});
