logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: console
      logFormat: "%-5p [%d] %c{5}: %m%n%rEx"

<#if ENABLE_METRICS??>
metrics:
  reporters:
    - type: influxdb
      protocol: http
      host: ${INFLUX_HOST}
      port: ${INFLUX_PORT}
      database: ${INFLUX_DB}
      auth: ${INFLUX_AUTH}
      tags:
        application: ${APPLICATION_NAME}
        namespace: ${NAMESPACE}
</#if>
