logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: console
      log_format: "%d{ISO8601, UTC} %highlight(%-5level) [%logger{36}]: %msg%n%yellow(%rEx) %nopex"

<#if MASTER_KEY_BASE64??>
master_key_base64: ${MASTER_KEY_BASE64}
</#if>

<#if ENABLE_METRICS??>
metrics:
  reporters:
    - type: influxdb
      protocol: http
      host: ${INFLUX_HOST}
      port: ${INFLUX_PORT}
      database: ${INFLUX_DB}
      auth: ${INFLUX_AUTH}
      tags:
        application: ${APPLICATION_NAME}
        namespace: ${NAMESPACE}
</#if>
