export const FETCH_DATASETS = "FETCH_DATASETS";
export const FETCH_DATASETS_SUCCESS = "FETCH_DATASETS_SUCCESS";
export const CREATE_DATASET = "CREATE_DATASET";
export const UI_SET_ACTIVE_MODAL = "UI_SET_ACTIVE_MODAL";
export const SEARCH_DATASETS = "SEARCH_DATASETS";
export const CREATE_DATASET_ERROR = "CREATE_DATASET_ERROR";
