image: quartic/npm-jdk

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
    - ./gradlew weyl-frontend:build
