version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:41

    working_directory: ~/zeus

    steps:
      - checkout

      # Yarn cache
      - restore_cache:
          keys:
            - zeus-{{ .Branch }}-yarn-{{ checksum "zeus-frontend/yarn.lock" }}
            - zeus-{{ .Branch }}-yarn
            - zeus-develop-yarn

      # TODO - Gradle cache

      - run:
          name: Install dependencies
          command: ./gradlew resolveConfigurations yarn_install --parallel --info --console=plain

      # Yarn cache
      - save_cache:
          key: zeus-{{ .Branch }}-yarn-{{ checksum "zeus-frontend/yarn.lock" }}
          paths:
            - zeus-frontend/node_modules

      # TODO - Gradle cache

      - run:
          name: Run tests
          command: ./gradlew check --info --console=plain --profile

      - store_test_results:
          path: zeus-backend/build/test-results/

      - setup_remote_docker:
          reusable: true

      - deploy:
          command: |
            gcloud-auth --with-docker
            ./gradlew dockerPush --parallel --info --console=plain