version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:41

    working_directory: ~/platform

    steps:
      - checkout

      - restore_cache:
          keys:
            # Can't specify an exact match, so hopefully branch + latest is good enough
            - platform-{{ .Branch }}-gradle
            - platform-develop-gradle

      - run:
          name: Install dependencies
          command: ./gradlew resolveConfigurations yarn --parallel --console=plain

      - run:
          name: Build artifacts and run tests
          command: |
            ./gradlew build --parallel --console=plain

      - run:
          name: Collect test results
          command: |
            mkdir -p /test-results
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} /test-results/ \;

      - store_test_results:
          path: /test-results/

      - store_artifacts:
          path: /test-results/

      - setup_remote_docker:
          reusable: true

      - deploy:
          command: |
            gcloud-auth --with-docker
            ./gradlew dockerPush --parallel --console=plain
      - run:
          name: Calculate Gradle checksum file
          command: find ~/.gradle -path ~/.gradle/daemon -prune -o -name '*' > /gradle.txt

      - save_cache:
          key: platform-{{ .Branch }}-gradle-{{ checksum "/gradle.txt" }}
          paths:
            - ~/.gradle

