version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:41

    working_directory: ~/platform

    steps:
      - checkout

      - restore_cache:
          keys:
            - platform-{{ .Branch }}-weyl-yarn-{{ checksum "weyl-frontend/yarn.lock" }}
            - platform-{{ .Branch }}-weyl-yarn
            - platform-develop-weyl-yarn

      - restore_cache:
          keys:
            - platform-{{ .Branch }}-mgmt-yarn-{{ checksum "mgmt-frontend/yarn.lock" }}
            - platform-{{ .Branch }}-mgmt-yarn
            - platform-develop-mgmt-yarn

      # TODO - Gradle cache

      - run:
          name: Install dependencies
          command: ./gradlew resolveConfigurations yarn_install --parallel --info --console=plain

      - save_cache:
          key: platform-{{ .Branch }}-weyl-yarn-{{ checksum "weyl-frontend/yarn.lock" }}
          paths:
            - weyl-frontend/node_modules

      - save_cache:
          key: platform-{{ .Branch }}-mgmt-yarn-{{ checksum "mgmt-frontend/yarn.lock" }}
          paths:
            - mgmt-frontend/node_modules


      # TODO - Gradle cache

      # We don't run --parallel because of Kotlin compiler bugs (see e.g. https://youtrack.jetbrains.com/issue/KT-10028)
      - run:
          name: Run tests
          command: ./gradlew check --info --console=plain --profile

      - run:
          name: Collect test results
          command: |
            mkdir -p ${CIRCLE_TEST_REPORTS}/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ${CIRCLE_TEST_REPORTS}/junit/ \;

      - store_test_results:
          path: ${CIRCLE_TEST_REPORTS}/junit/

      - setup_remote_docker:
          reusable: true

      - deploy:
          command: |
            gcloud-auth --with-docker
            ./gradlew dockerPush --parallel --info --console=plain