const PREFIX = "weyl/home";

export const SEARCH = `${PREFIX}/SEARCH`;
export const SEARCH_DONE = `${PREFIX}/SEARCH_DONE`;
export const BUCKET_COMPUTATION_START = `${PREFIX}/BUCKET_COMPUTATION_START`;

export const UI_TOGGLE = `${PREFIX}/UI_TOGGLE`;
export const CLEAR_SELECTION = `${PREFIX}/CLEAR_SELECTION`;

export const LAYER_CREATE = `${PREFIX}/LAYER_CREATE`;
export const LAYER_TOGGLE_VISIBLE = `${PREFIX}/LAYER_TOGGLE_VISIBLE`;
export const LAYER_CLOSE = `${PREFIX}/LAYER_CLOSE`;
export const LAYER_SET_STYLE = `${PREFIX}/LAYER_SET_STYLE`;
export const LAYER_TOGGLE_VALUE_VISIBLE = `${PREFIX}/LAYER_TOGGLE_VALUE_VISIBLE`;
export const LAYER_SET_DATA = `${PREFIX}/LAYER_SET_DATA`;

export const MAP_LOADING = `${PREFIX}/MAP_LOADING`;
export const MAP_LOADED = `${PREFIX}/MAP_LOADED`;
export const MAP_MOUSE_MOVE = `${PREFIX}/MAP_MOUSE_MOVE`;
export const MAP_MOUSE_CLICK = `${PREFIX}/MAP_MOUSE_CLICK`;

export const GEOFENCE_EDIT_START = `${PREFIX}/GEOFENCE_EDIT_START`;
export const GEOFENCE_EDIT_FINISH = `${PREFIX}/GEOFENCE_EDIT_FINISH`;
export const GEOFENCE_EDIT_CHANGE = `${PREFIX}/GEOFENCE_EDIT_CHANGE`;
export const GEOFENCE_SAVE_DONE = `${PREFIX}/GEOFENCE_SAVE_DONE`;
export const GEOFENCE_CHANGE_TYPE = `${PREFIX}/GEOFENCE_CHANGE_TYPE`;

export const FEED_SET_DATA = `${PREFIX}/FEED_SET_DATA`;

export const CONNECTION_UP = `${PREFIX}/CONNECTION_UP`;
export const CONNECTION_DOWN = `${PREFIX}/CONNECTION_DOWN`;

export const SELECTION_INFO_LOADING = `${PREFIX}/SELECTION_INFO_LOADING`;
export const SELECTION_INFO_LOADED = `${PREFIX}/SELECTION_INFO_LOADED`;
export const SELECTION_INFO_FAILED_TO_LOAD = `${PREFIX}/SELECTION_INFO_FAILED_TO_LOAD`;
