const PREFIX = "weyl/home";

export const LAYER_COMPUTATION_START = `${PREFIX}/LAYER_COMPUTATION_START`;

export const UI_TOGGLE = `${PREFIX}/UI_TOGGLE`;
export const UI_SET_THEME = `${PREFIX}/UI_SET_THEME`;

export const CLEAR_SELECTION = `${PREFIX}/CLEAR_SELECTION`;

export const LAYER_LIST_UPDATE = `${PREFIX}/LAYER_LIST_UPDATE`;

export const LAYER_CREATE = `${PREFIX}/LAYER_CREATE`;
export const LAYER_TOGGLE_VISIBLE = `${PREFIX}/LAYER_TOGGLE_VISIBLE`;
export const LAYER_CLOSE = `${PREFIX}/LAYER_CLOSE`;
export const LAYER_SET_STYLE = `${PREFIX}/LAYER_SET_STYLE`;
export const LAYER_TOGGLE_VALUE_VISIBLE = `${PREFIX}/LAYER_TOGGLE_VALUE_VISIBLE`;
export const LAYER_APPLY_TIME_RANGE_FILTER = `${PREFIX}/LAYER_APPLY_TIME_RANGE_FILTER`;
export const LAYER_UPDATE = `${PREFIX}/LAYER_UPDATE`;

export const MAP_LOADING = `${PREFIX}/MAP_LOADING`;
export const MAP_LOADED = `${PREFIX}/MAP_LOADED`;
export const MAP_MOUSE_MOVE = `${PREFIX}/MAP_MOUSE_MOVE`;
export const MAP_MOUSE_CLICK = `${PREFIX}/MAP_MOUSE_CLICK`;

export const GEOFENCE_PANE_TOGGLE_VISIBILITY = `${PREFIX}/GEOFENCE_PANE_TOGGLE_VISIBILITY`;
export const GEOFENCE_COMMIT_SETTINGS = `${PREFIX}/GEOFENCE_COMMIT_SETTINGS`;
export const GEOFENCE_SET_MANUAL_CONTROLS_VISIBILITY = `${PREFIX}/GEOFENCE_SET_MANUAL_CONTROLS_VISIBILITY`;
export const GEOFENCE_SET_MANUAL_GEOMETRY = `${PREFIX}/GEOFENCE_SET_MANUAL_GEOMETRY`;
export const GEOFENCE_SET_GEOMETRY = `${PREFIX}/GEOFENCE_SET_GEOMETRY`;
export const GEOFENCE_SET_VIOLATIONS = `${PREFIX}/GEOFENCE_SET_VIOLATIONS`;
export const GEOFENCE_TOGGLE_ALERTS = `${PREFIX}/GEOFENCE_TOGGLE_ALERTS`;

export const CONNECTION_UP = `${PREFIX}/CONNECTION_UP`;
export const CONNECTION_DOWN = `${PREFIX}/CONNECTION_DOWN`;

export const SELECTION_SENT = `${PREFIX}/SELECTION_STATUS_SENT`;

export const SUBSCRIPTIONS_POST = `${PREFIX}/SUBSCRIPTIONS_POST`;
