export const FETCH_DATASETS = "FETCH_DATASETS";
export const FETCH_DATASETS_SUCCESS = "FETCH_DATASETS_SUCCESS";
export const CREATE_DATASET = "CREATE_DATASET";
export const UI_SET_ACTIVE_MODAL = "UI_SET_ACTIVE_MODAL";
export const SEARCH_DATASETS = "SEARCH_DATASETS";
export const SELECT_NAMESPACE = "SELECT_NAMESPACE";
export const CREATE_DATASET_ERROR = "CREATE_DATASET_ERROR";
export const DELETE_DATASET = "DELETE_DATASET";

export const FETCH_PIPELINE = "FETCH_PIPELINE";
export const FETCH_PIPELINE_SUCCESS = "FETCH_PIPELINE_SUCCESS";
export const FETCH_PIPELINE_NOT_FOUND = "FETCH_PIPELINE_NOT_FOUND";

export const FETCH_FEED = "FETCH_FEED";
export const FETCH_FEED_SUCCESS = "FETCH_FEED_SUCCESS";

export const USER_LOGIN_GITHUB = "USER_LOGIN_GITHUB";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_FETCH_PROFILE_SUCCESS = "USER_FETCH_PROFILE_SUCCESS";


